apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: your-ecr-repository-uri:latest
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: api-key
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: db-password
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  app-config.yml: |-
    some-config-key: some-config-value
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  api-key: BASE64_ENCODED_API_KEY
  db-username: BASE64_ENCODED_DB_USERNAME
  db-password: BASE64_ENCODED_DB_PASSWORD
